# Generated by Django 4.1.7 on 2023-04-03 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LinkToTodoItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=65)),
                ("url", models.URLField()),
                (
                    "todo_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.todoitem"
                    ),
                ),
            ],
        ),
    ]
